### ISSUE TITLE
Multiple templates

### ISSUE THREAD

**Issue by HamedFathi** [itgalaxy/nunjucks-webpack-plugin#1]
Hi

I have this

```
const njks = path.join(__dirname, 'Nunjucks', '**', '*.@(njk|nunjucks)');
const njkFiles = glob.sync(njks);
```

How to configure your plugin with multiple .njk templates ?
your snippet code have one .njk and one template`s result.

**Comment by evilebottnawi** [comment]
@HamedFathi you can use `template:[{from: 'foo.njk', to: 'bar'}, {from: 'bar.njk', to: 'foo'}]` options for multiple templates

**Comment by HamedFathi** [comment]
@evilebottnawi 

Thanks yes it works, please add this tip to your README.md.
