### ISSUE TITLE
writeToFileWhenMemoryFS seems broken

### ISSUE THREAD

**Issue by aendrew** [itgalaxy/nunjucks-webpack-plugin#6]
When I set writeToFileWhenMemoryFS, it seems Nunjucks compilation doesn't occur.

**Comment by evilebottnawi** [comment]
@aendrew can your describe more details, your error message, configuration or minimum reproducible test repo?

**Comment by aendrew** [comment]
@evilebottnawi Here's a minimal rep test case repo: https://github.com/aendrew/6-nunjucks-webpack-plugin

With `writeToFileWhenMemoryFS` enabled, `webpack-dev-server` doesn't serve out any kind of rendered HTML template.

**Comment by pauleveritt** [comment]
FWIW, in the test case for @aendrew running the broken flavor generates:

```
(node:46194) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EACCES: permission denied, open '/index.html'
(node:46194) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
webpack: wait until bundle finished: /
```

webpack-dev-server then doesn't detect any changes to anything after that.
