### ISSUE TITLE
Webpack 4 Support?

### ISSUE THREAD

**Issue by burt202** [itgalaxy/nunjucks-webpack-plugin#8]
Do we know if this plugin has support for webpack v4? I have a relatively simple setup and am getting the following error:

```
TypeError: compilation.fileDependencies.indexOf is not a function
    at fileDependencies.forEach.file (/....../node_modules/nunjucks-webpack-plugin/src/NunjucksWebpackPlugin.js:107:42)
```

Any ideas?

**Comment by evilebottnawi** [comment]
@burt202 need PR for solve this problem, PR welcome :+1:

**Comment by burt202** [comment]
PR created at https://github.com/itgalaxy/nunjucks-webpack-plugin/pull/9
